sessions:
  cycle: 5
freeswitch:
- host: "127.0.0.1"
  port: "8021"
  pass: "pass"
  retry_number: 10
- host: "127.0.0.1"
  port: "8021"
  pass: "pass"
  retry_number: 10
- host: "127.0.0.1"
  port: "8021"
  pass: "pass"
  retry_number: 10
database:
  host: "127.0.0.1"
  port: "3306"
  user: "user"
  pass: "pass"
  dbname: "dbname"
redis:
  host: "localhost"
  port: "6379"
  pass: ""
  db: 0
grcp_listener:
  port: 9000